### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by theodorosploumis** [gtramontina/h-factors#7]
Hi,

since this collections of hypermedia Specs is so useful I am wondering if it is still maintained. Are the maintainers of the Specs evolved to update their spec accordingly (eg with an issue on their repositories)?
If it is not maintained I am available to help! I know I could do a fork but this is not fair.

Generally speaking, I believe that it needs a better content, title and description as also as some seo because it is not easy to discover through search engines. And it is so useful that should not be kept "hidden".

Thanks for your time.

**Comment by gtramontina** [comment]
Hey there…
It is active as I maintain it, take PRs in and everything. The spec writers are not directly involved, though. When I first put this together, I've tweeted it to some (if not all) of the spec writers. My intent was for it to be as simple as possible in terms of information consumption. But you're right, I have not put much effort in SEO or spreading the word. I'd really welcome any help! After all, this is an [OPEN Open Source](http://openopensource.org/) little project! 😄 

I'm adding you as a collaborator.
